### ISSUE TITLE
Serenade doesn't load scripts recursively anymore

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [serenadeai/custom-commands#7]
I just cloned this and realized that the commands in `all.js` only work if I move them to the root of `scripts`.

Side note: `commandOrControl` is apparently outdated.

```
os: 
  platform: win32
  release: 10.0.19043
version: 1.6.2
application: serenade
```
